server:
  port: 9020

# eureka 注册中心配置
eureka:
  instance:
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5 # 服务注册更新时间间隔（默认30秒）
    lease-expiration-duration-in-seconds: 10 # 服务注册到期时间（默认90秒）
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.ip-address}:${server.port}/eureka
  healthcheck:
    enabled: true # 开启健康检查（需要spring-boot-starter-actuator依赖）

# zuul 路由配置
zuul:
  host:
    connect-timeout-millis: 3000
    socket-timeout-millis: 3000

# 数据库配置
spring:
  redis:
    database: 0
    host: 118.24.159.161
    password: 2550767776
    port: 6379
    timeout: 3000 #  连接超时时间 单位 ms（毫秒）
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.24.159.161.com:3306/aiyo?characterEncoding=utf8
    username: root
    password: 2550767776

# logging
logging:
  path: root-log\gateway
  level:
    com.aiyo: debug
    jdbc:
      sqltiming: INFO
      sqlonly: OFF
      audit: OFF
      resultset: OFF
      connection: OFF
