spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://118.24.159.161:3306/aiyo?characterEncoding=utf8
    username: root
    password: 2550767776

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.vtest.entity
  configuration:
    variables:
      k1: com.vtest.config.Constat
